databases:
  - name: linkeadisimo
    databaseName: linkeadisimo
    user: dylan

services:
  - type: web
    name: linkeadisimo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn linkeadisimo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linkeadisimo
          property: connectionString
      - key: LINKEADISIMO_SECRET
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4