# Generated by Django 3.0.1 on 2019-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
