# Generated by Django 4.1.3 on 2023-01-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
