# Generated by Django 4.1.3 on 2023-01-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_comment_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="domain",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
