# Generated by Django 3.0.2 on 2020-01-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200111_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.Publication'),
            preserve_default=False,
        ),
    ]
