# Generated by Django 3.0.2 on 2020-01-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publication',
        ),
    ]
