# Generated by Django 3.0.1 on 2020-01-09 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_remove_publication_is_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=8192)),
                ('votes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, on_delete=models.SET(None), to='website.Comment')),
                ('publication', models.ForeignKey(on_delete=models.SET(None), to='website.Publication')),
            ],
        ),
    ]
