# Generated by Django 3.0.2 on 2020-01-12 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_comment_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(related_name='com_voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='voters',
            field=models.ManyToManyField(related_name='pub_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
